//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.Configs
{
   
public partial class TbEntityData
{
    private readonly Dictionary<int, Configs.EntityData> _dataMap;
    private readonly List<Configs.EntityData> _dataList;
    
    public TbEntityData(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, Configs.EntityData>();
        _dataList = new List<Configs.EntityData>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Configs.EntityData _v;
            _v = Configs.EntityData.DeserializeEntityData(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Configs.EntityData> DataMap => _dataMap;
    public List<Configs.EntityData> DataList => _dataList;

    public Configs.EntityData GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Configs.EntityData Get(int key) => _dataMap[key];
    public Configs.EntityData this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}